services:
  - type: web
    name: chesswebbackend
    runtime: node
    rootDir: server
    plan: free
    buildCommand: npm install
    startCommand: npm start
    autoDeployTrigger: commits
    healthCheckPath: /healthz
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URL
        sync: false
      - key: CLIENT_ORIGINS
        sync: false
      - key: GOOGLE_CLIENT_ID
        value: 588502511960-gkf4hgkja7pu0drehngcan9hk5d452ii.apps.googleusercontent.com
      - key: FACEBOOK_APP_ID
        value: "1481421286715852"
      - key: ALLOW_VERCEL_PREVIEWS
        value: "true"
